version: 2
jobs:
  build:
    docker:
      - image: bitspark/slang-ci:latest
    working_directory: ~/slang-ui
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install
          command: |
            npm install
            npm install -g @angular/cli@latest
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: ng build --prod --output-path=dist
      - persist_to_workspace:
          root: ~/slang-ui
          paths:
            - dist
  release:
    docker:
      - image: bitspark/slang-ci:latest
    working_directory: ~/slang-ui
    steps:
      - checkout
      - attach_workspace:
          at: ~/slang-ui
      - run:
          name: Package
          command: |
            python3 ./ci/package.py ${CIRCLE_TAG}
      - run:
          name: Release
          command: ${GOPATH}/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./ci/release/
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
